services:
  postgres:
    image: postgres:latest
    container_name: vascomm-psql
    environment:
      POSTGRES_USER: vascomm
      POSTGRES_PASSWORD: vascomm
      POSTGRES_DB: vascomm
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
